export const SET_CHARACTERS = 'SET_CHARACTERS';
export const SET_CURRENT_CHARACTER = 'SET_CURRENT_CHARACTER';
export const SET_CHARACTERS_FROM_FIELD = 'SET_CHARACTERS_FROM_FIELD';
export const UPDATE_CHARACTERS = 'UPDATE_CHARACTERS';
